import { baseFields, fieldsFor, modules, records, roles, vendors } from "/data.js";
import { bindWorkflow, workflowPanel } from "/workflow.js";

const state = { module: routeModule(), role: localStorage.getItem("nv-role") || "Procurement", tab: "details", page: 1 };
const root = document.getElementById("app-root");

function routeModule(){ const path=location.pathname.replace(/^\/+|\/+$/g,""); return modules.find(m=>m.key===path)?.key || "dashboard"; }
function sid(...parts){ return `nv-${parts.map(p=>String(p).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")).filter(Boolean).join("-")}`; }
function esc(value){ return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])); }
function activeModule(){ return modules.find(m=>m.key===state.module) || modules[0]; }
function statusClass(value){ const v=String(value).toLowerCase(); return /high|exception|hold|escalated/.test(v)?"danger":/pending|review|medium|draft|conditional/.test(v)?"warn":""; }

function shell(){
  const current=activeModule();
  root.innerHTML=`<header class="topbar"><div class="brand"><span class="brand-mark">N</span><span>NexusVendor</span></div><div class="global-search"><label class="hidden" for="${sid("global","search")}">Global search</label><input id="${sid("global","search")}" type="search" placeholder="Search vendors, contracts, invoices, documents..."></div><div class="top-actions"><button id="${sid("global","notifications")}" class="icon-btn" aria-label="Notifications" title="Notifications">●</button><button id="${sid("global","tasks")}" class="icon-btn" aria-label="My tasks" title="My tasks">✓</button><label class="hidden" for="${sid("global","role")}">Active role</label><select id="${sid("global","role")}" class="role-select">${roles.map(r=>`<option${r===state.role?" selected":""}>${r}</option>`).join("")}</select><button id="${sid("global","profile")}" class="icon-btn" aria-label="User profile" title="Maya Chen">MC</button></div></header><aside class="sidebar" aria-label="Main navigation">${nav()}</aside><main class="main"><section class="page-head"><div class="breadcrumbs">NexusVendor / ${esc(current.group)} / ${esc(current.title)}</div><div class="page-title-row"><div><h1 class="page-title">${esc(current.title)}</h1><p class="page-subtitle">Enterprise ${esc(current.title.toLowerCase())} operations and control workspace</p></div><div class="page-actions"><button id="${sid(current.key,"export")}" class="btn">Export</button><button id="${sid(current.key,"new")}" class="btn primary">+ New record</button></div></div></section><div id="${sid(current.key,"content")}" class="content">${page()}</div></main><div id="${sid("global","overlay")}"></div>`;
  bind();
}
function nav(){ let last=""; return modules.map(m=>{const group=m.group!==last?`<div class="nav-group">${esc(m.group)}</div>`:"";last=m.group;return `${group}<a id="${sid("nav",m.key)}" class="nav-link ${m.key===state.module?"active":""}" href="${m.path}"><span class="nav-icon">${m.key.slice(0,1).toUpperCase()}</span><span>${esc(m.title)}</span></a>`}).join(""); }
function metrics(){ const values=state.module==="dashboard"?[["Active vendors","1,284","+3.2% this quarter"],["Managed spend","$184.6M","72% under contract"],["Open approvals","43","11 due today"],["High risks","17","-4 since last month"]]:[["Active records","248","+12 this month"],["Pending action","31","8 due today"],["Exceptions","7","2 require escalation"],["Cycle time","4.2 days","-0.8 day improvement"]];return `<div class="metrics">${values.map((x,i)=>`<article class="metric"><div class="metric-label">${x[0]}</div><div class="metric-value">${x[1]}</div><div class="metric-note">${x[2]}</div></article>`).join("")}</div>`; }
function page(){ return `${metrics()}${workflowPanel(state.module)}${listCard()}${workspaceCard()}`; }
function rowsFor(){ if(state.module==="vendors"||state.module==="onboarding") return vendors.map(v=>[v.id,v.name,v.category,v.status,v.risk,v.owner]); if(state.module==="documents") return [["DOC-004821","Information Security Policy","Policy","v4.2","Approved","2027-03-31"],["DOC-004833","Asteron Cloud Services MSA","Contract","v7.0","Executed","2027-01-31"],["DOC-004849","Meridian Security Questionnaire","Assessment","v2.1","Review","2026-08-01"],["DOC-004855","Invoice Processing SOP","Procedure","v3.4","Approved","2027-05-15"],["DOC-004872","Q2 Vendor Risk Report","Report","v1.0","Published","2026-09-30"]]; if(state.module==="administration") return [["USR-00142","Maya Chen","Procurement","Active","North America","2026-07-13"],["USR-00158","Daniel Okafor","Risk","Active","EMEA","2026-07-12"],["USR-00173","Sofia Alvarez","Legal","Active","LATAM","2026-07-11"]]; return records[state.module]||records.approvals; }
function listCard(){ const rows=rowsFor(); const heads=state.module==="vendors"||state.module==="onboarding"?["ID","Name","Category","Status","Risk","Owner"]:["Reference","Description / Party","Category / Link","Status / Value","Due / State","Date / Owner"];const docFiles=["0001-asteron-cloud-services-information-security-policy.md","0002-asteron-cloud-services-master-services-agreement.md","0003-asteron-cloud-services-supplier-code-of-conduct.md","0004-asteron-cloud-services-invoice-processing-sop.md","0005-asteron-cloud-services-security-questionnaire.md"];return `<section class="card"><div class="card-head"><h2 class="card-title">Records</h2><div class="toolbar spacer">${state.module==="documents"?`<a id="${sid("documents","corpus","index")}" class="btn" href="/public/documents/index.json" target="_blank">Corpus index (300)</a>`:""}<label class="hidden" for="${sid(state.module,"list","filter")}">Filter records</label><input id="${sid(state.module,"list","filter")}" type="search" placeholder="Filter records"><label class="hidden" for="${sid(state.module,"list","status")}">Status</label><select id="${sid(state.module,"list","status")}"><option>All statuses</option><option>Open</option><option>Pending</option><option>Approved</option></select><button id="${sid(state.module,"list","columns")}" class="btn">Columns</button></div></div><div style="overflow:auto"><table class="data-table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join("")}<th>Actions</th></tr></thead><tbody>${rows.map((row,ri)=>`<tr>${row.map((v,ci)=>`<td>${ci===0?`<a id="${sid(state.module,"row",ri+1,"open")}" class="table-link" href="${state.module==="documents"?`/public/documents/${docFiles[ri]}`:`#record-${ri+1}`}"${state.module==="documents"?' target="_blank"':""}>${esc(v)}</a>`:ci===3||ci===4?`<span class="badge ${statusClass(v)}">${esc(v)}</span>`:esc(v)}</td>`).join("")}<td><button id="${sid(state.module,"row",ri+1,"menu")}" class="icon-btn" aria-label="Actions for ${esc(row[0])}">⋮</button></td></tr>`).join("")}</tbody></table></div><div class="pager"><span>Showing 1-${rows.length} of ${state.module==="documents"?300:248}</span><div class="pager-actions"><button id="${sid(state.module,"page","previous")}" class="btn" disabled>Previous</button><button id="${sid(state.module,"page","next")}" class="btn">Next</button></div></div></section>`; }
function workspaceCard(){ return `<section class="card"><div class="tabs" role="tablist">${["details","line-items","approvals","documents","audit-history"].map(t=>`<button id="${sid(state.module,"tab",t)}" class="tab ${state.tab===t?"active":""}" role="tab" aria-selected="${state.tab===t}">${t.split("-").map(x=>x[0].toUpperCase()+x.slice(1)).join(" ")}</button>`).join("")}</div><div class="card-body">${tabContent()}</div></section>`; }
function tabContent(){ if(state.tab==="details") return form(); if(state.tab==="line-items") return repeatable(); if(state.tab==="approvals") return approval(); if(state.tab==="documents") return documents(); return audit(); }
function fieldHtml(field,index){ const id=sid(state.module,"details",field.key); const required=index<4?` required aria-required="true"`:""; const label=`<label for="${id}">${esc(field.label)}${index<4?' <span class="required">*</span>':""}</label>`; const options=[field.value,"Approved","Pending Review","High","Medium","Low"].filter((v,i,a)=>a.indexOf(v)===i); if(field.type==="textarea")return `<div class="field wide">${label}<textarea id="${id}" class="control"${required}>${esc(field.value)}</textarea></div>`;if(field.type==="richtext")return `<div class="field wide">${label}<div class="rich-toolbar"><button id="${id}-bold" type="button"><b>B</b></button> <button id="${id}-list" type="button">List</button></div><textarea id="${id}" class="control">${esc(field.value)}</textarea></div>`;if(field.type==="select")return `<div class="field">${label}<select id="${id}" class="control">${options.map(o=>`<option>${esc(o)}</option>`).join("")}</select></div>`;if(field.type==="multiselect")return `<div class="field">${label}<select id="${id}" class="control" multiple><option selected>North America</option><option selected>EMEA</option><option>APAC</option><option>LATAM</option></select></div>`;if(field.type==="checkbox"||field.type==="toggle")return `<div class="field"><label>${esc(field.label)}</label><div class="check-row"><input id="${id}" ${field.type==="toggle"?'class="toggle"':''} type="checkbox" ${field.value==="true"?"checked":""}><label for="${id}">${field.type==="toggle"?"Enabled":"Confirmed"}</label></div></div>`;if(field.type==="radio")return `<fieldset class="field"><legend>${esc(field.label)}</legend><div class="radio-row">${["Approve","Reject","Return"].map((o,i)=>`<input id="${id}-${o.toLowerCase()}" name="${id}" type="radio" ${i===0?"checked":""}><label for="${id}-${o.toLowerCase()}">${o}</label>`).join("")}</div></fieldset>`;if(field.type==="signature")return `<div class="field">${label}<input id="${id}" class="control signature" value="${esc(field.value)}"></div>`;return `<div class="field">${label}<input id="${id}" class="control" type="${field.type}" value="${field.type==='file'?'':esc(field.value)}"${required}><div class="help">${field.type==="password"?"Minimum 12 characters":"Verified enterprise data"}</div></div>`; }
function form(){ const fields=fieldsFor(state.module); return `<form id="${sid(state.module,"details","form")}" novalidate><details id="${sid(state.module,"details","general")}" class="accordion" open><summary id="${sid(state.module,"details","general","summary")}">General information</summary><div class="accordion-content form-grid">${fields.slice(0,20).map(fieldHtml).join("")}</div></details><details id="${sid(state.module,"details","controls")}" class="accordion" open><summary id="${sid(state.module,"details","controls","summary")}">Financial, ownership, and control data</summary><div class="accordion-content form-grid">${fields.slice(20).map((f,i)=>fieldHtml(f,i+20)).join("")}<div id="${sid(state.module,"details","conditional-panel")}" class="field full conditional"><strong>Conditional review fields</strong><p>Visible because this record is confidential. Complete enhanced review before submission.</p><label for="${sid(state.module,"details","conditional-reason")}">Enhanced review rationale</label><textarea id="${sid(state.module,"details","conditional-reason")}" class="control">Confidential information is limited to authorized reviewers.</textarea></div></div></details><div class="toolbar"><button id="${sid(state.module,"details","save-draft")}" class="btn" type="button">Save draft</button><button id="${sid(state.module,"details","validate")}" class="btn" type="button">Validate</button><button id="${sid(state.module,"details","submit")}" class="btn primary" type="submit">Submit for approval</button></div></form>`; }
function repeatable(){ return `<div class="toolbar"><button id="${sid(state.module,"lines","add")}" class="btn primary">+ Add line</button><button id="${sid(state.module,"lines","import")}" class="btn">Import lines</button></div><table class="data-table"><thead><tr><th>Line</th><th>Description</th><th>Quantity</th><th>Unit price</th><th>Tax %</th><th>Total</th><th></th></tr></thead><tbody>${[1,2,3].map(i=>`<tr><td>${i}</td><td><input id="${sid(state.module,"line",i,"description")}" class="control" value="Enterprise service line ${i}"></td><td><input id="${sid(state.module,"line",i,"quantity")}" class="control" type="number" value="${i*5}"></td><td><input id="${sid(state.module,"line",i,"price")}" class="control" type="number" value="12500"></td><td><input id="${sid(state.module,"line",i,"tax")}" class="control" type="number" value="8.25"></td><td>$${(i*62500).toLocaleString()}</td><td><button id="${sid(state.module,"line",i,"remove")}" class="icon-btn" aria-label="Remove line ${i}">×</button></td></tr>`).join("")}</tbody></table>`; }
function approval(){ return `<div class="split"><div class="timeline">${[["Submitted","Maya Chen","2026-07-11 09:14"],["Procurement review","Oliver Grant","2026-07-11 14:42"],["Finance approval","Pending","Due 2026-07-15"]].map((x,i)=>`<div class="timeline-item"><strong>${x[0]}</strong><div>${x[1]}</div><small>${x[2]}</small>${i===2?`<div><button id="${sid(state.module,"approval","approve")}" class="btn primary">Approve</button> <button id="${sid(state.module,"approval","return")}" class="btn">Return</button></div>`:""}</div>`).join("")}</div><div><label for="${sid(state.module,"approval","comment")}">Approval comment</label><textarea id="${sid(state.module,"approval","comment")}" class="control" placeholder="Enter decision rationale"></textarea></div></div>`; }
function documents(){ return `<div class="toolbar"><label class="btn" for="${sid(state.module,"documents","upload")}">Upload document</label><input id="${sid(state.module,"documents","upload")}" class="hidden" type="file" multiple><a id="${sid(state.module,"documents","library")}" class="btn" href="/documents">Open library</a></div><table class="data-table"><thead><tr><th>Document</th><th>Type</th><th>Version</th><th>Owner</th><th>Status</th></tr></thead><tbody>${[["Master Services Agreement","Contract","7.0","Sofia Alvarez","Executed"],["Security Assessment","Questionnaire","2.1","Daniel Okafor","Review"],["Insurance Certificate","Certificate","1.0","Vendor","Approved"]].map((r,i)=>`<tr>${r.map((v,j)=>`<td>${j===0?`<a id="${sid(state.module,"document",i+1)}" class="table-link" href="#document-${i+1}">${v}</a>`:`${v}`}</td>`).join("")}</tr>`).join("")}</tbody></table>`; }
function audit(){ return `<div class="timeline">${[["Record updated","Maya Chen changed payment terms from Net 30 to Net 45","2026-07-13 10:42:18"],["Evidence attached","Daniel Okafor uploaded security-assessment-v2.pdf","2026-07-12 16:05:31"],["Workflow started","System initiated Finance and Legal parallel review","2026-07-11 09:14:02"]].map((x,i)=>`<div class="timeline-item"><strong>${x[0]}</strong><p>${x[1]}</p><small>${x[2]} · Event EVT-${80421+i}</small></div>`).join("")}</div>`; }

function modal(){ document.getElementById(sid("global","overlay")).innerHTML=`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="${sid(state.module,"modal","title")}"><div class="modal-head"><h2 id="${sid(state.module,"modal","title")}" class="card-title">Create ${esc(activeModule().title)} record</h2><button id="${sid(state.module,"modal","close")}" class="icon-btn spacer" aria-label="Close dialog">×</button></div><div class="modal-body form-grid">${baseFields.slice(0,8).map(fieldHtml).join("")}</div><div class="modal-foot"><button id="${sid(state.module,"modal","cancel")}" class="btn">Cancel</button><button id="${sid(state.module,"modal","create")}" class="btn primary">Create record</button></div></section></div>`; ["close","cancel"].forEach(x=>document.getElementById(sid(state.module,"modal",x)).onclick=()=>document.getElementById(sid("global","overlay")).innerHTML="");document.getElementById(sid(state.module,"modal","create")).onclick=()=>{document.getElementById(sid("global","overlay")).innerHTML="";toast("Record created and routed to the appropriate workflow.")}; }
function toast(message){ const el=document.createElement("div");el.id=sid("global","toast");el.className="toast";el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),3500); }
function bind(){ document.getElementById(sid("global","role")).onchange=e=>{state.role=e.target.value;localStorage.setItem("nv-role",state.role);toast(`Role changed to ${state.role}`)};document.getElementById(sid(state.module,"new")).onclick=modal;document.getElementById(sid(state.module,"export")).onclick=()=>toast("Export prepared. This training environment does not transmit data.");document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{state.tab=b.id.replace(sid(state.module,"tab")+"-","");shell()});bindWorkflow(state.module,message=>{toast(message);shell()});const form=document.getElementById(sid(state.module,"details","form"));if(form){form.onsubmit=e=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();return}toast("Record submitted for approval.")};document.getElementById(sid(state.module,"details","save-draft")).onclick=()=>toast("Draft saved locally.");document.getElementById(sid(state.module,"details","validate")).onclick=()=>toast(form.checkValidity()?"Validation completed successfully.":"Validation found required fields.")}document.querySelectorAll('a[href^="#"]').forEach(a=>a.onclick=e=>{e.preventDefault();toast(`Opened ${a.textContent.trim()}`)}); }

shell();
