const KEY="nexusvendor-demo-workflow-v1";
export const workflowModules=["vendors","onboarding","procurement","rfps","purchase-orders","contracts"];
const defs={
 vendorName:["nv-workflow-vendor-name","Vendor name"],vendorId:["nv-workflow-vendor-id","Vendor ID"],taxId:["nv-workflow-tax-id","Tax identifier"],country:["nv-workflow-country","Registration country"],primaryEmail:["nv-workflow-primary-email","Primary contact email"],serviceCategory:["nv-workflow-service-category","Service category"],expectedSpend:["nv-workflow-expected-spend","Expected annual spend"],dataClassification:["nv-workflow-data-classification","Data classification"],onboardingCaseId:["nv-workflow-onboarding-case-id","Onboarding case ID"],procurementRequestId:["nv-workflow-procurement-request-id","Procurement request ID"],rfpId:["nv-workflow-rfp-id","RFP ID"],purchaseOrderId:["nv-workflow-purchase-order-id","Purchase order ID"]
};
const configs={
 vendors:{help:"Enter the authoritative vendor identity. NexusVendor generates the reusable identity and initial risk values.",fields:[["vendorName"],["taxId"],["country","select",["United States","United Kingdom","Germany","India","Singapore","Australia"]],["primaryEmail","email"],["serviceCategory","select",["Technology services","Professional services","Logistics","Facilities","Laboratory services"]],["expectedSpend","number"]],local:[],generated:[["vendorId","Vendor ID"],["normalizedName","Normalized vendor name"],["riskTier","Initial risk tier"],["createdDate","Record created date"]]},
 onboarding:{help:"Re-enter the recorded identity and add due-diligence facts. Submission generates values required downstream.",fields:[["vendorName"],["vendorId"],["taxId"],["primaryEmail","email"],["dataClassification","select",["Public","Internal","Confidential","Restricted"]]],local:[["criticalService","Critical service"],["personalDataVolume","Annual personal data records","number"],["targetGoLive","Target go-live date","date"]],generated:[["onboardingCaseId","Onboarding case ID"],["onboardingDueDate","Onboarding due date"],["riskScore","Inherent risk score"],["reviewRoute","Required review route"]]},
 procurement:{help:"This form starts blank intentionally. A trained agent should reuse the values recorded on the first two pages.",fields:[["vendorName"],["vendorId"],["onboardingCaseId"],["serviceCategory"],["expectedSpend","number"]],local:[["requestTitle","Request title"],["requiredByDate","Required-by date","date"],["businessJustification","Business justification"]],generated:[["procurementRequestId","Procurement request ID"],["budgetClassification","Budget classification"],["approvalRoute","Approval route"],["createdDate","Request created date"]]},
 rfps:{help:"Create a sourcing event using the recorded vendor and approved procurement request references.",fields:[["vendorName"],["vendorId"],["procurementRequestId"],["serviceCategory"],["expectedSpend","number"]],local:[["eventTitle","Sourcing event title"],["responseDays","Supplier response period (days)","number","21"],["technicalWeight","Technical evaluation weight (%)","number","60"]],generated:[["rfpId","RFP ID"],["issueDate","RFP issue date"],["responseDeadline","Response deadline"],["commercialWeight","Commercial evaluation weight (%)"]]},
 "purchase-orders":{help:"Create the purchase order using the recorded vendor, request, and sourcing event data.",fields:[["vendorName"],["vendorId"],["procurementRequestId"],["rfpId"],["expectedSpend","number"]],local:[["currency","Transaction currency","text","USD"],["paymentTerms","Payment terms","text","Net 45"],["deliveryDate","Delivery date","date"]],generated:[["purchaseOrderId","Purchase order ID"],["purchaseOrderDate","Purchase order date"],["purchaseOrderTotal","Purchase order total"],["purchaseOrderStatus","Purchase order status"]]},
 contracts:{help:"Finalize the contract using the same identity and generated references from the earlier pages.",fields:[["vendorName"],["vendorId"],["onboardingCaseId"],["procurementRequestId"],["purchaseOrderId"],["dataClassification"]],local:[["agreementTitle","Agreement title"],["termMonths","Initial term (months)","number","36"]],generated:[["contractId","Contract ID"],["startDate","Contract start date"],["endDate","Contract end date"],["reviewDate","Contract review date"]]}
};
const empty=()=>({source:{},steps:{},completed:[]});
const load=()=>{try{return{...empty(),...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return empty()}};
const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const hash=v=>{let n=17;for(const c of v)n=(n*31+c.charCodeAt(0))%100000;return String(n).padStart(5,"0")};
const today=()=>new Date().toISOString().slice(0,10);
const plus=(date,days)=>{const d=new Date(`${date}T12:00:00`);d.setDate(d.getDate()+Number(days));return d.toISOString().slice(0,10)};
const money=v=>Number(v||0).toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
const localId=(module,key)=>`nv-workflow-${module}-${key.replace(/[A-Z]/g,c=>`-${c.toLowerCase()}`)}`;
function sharedField([key,type="text",options=[]],value=""){
 const [id,label]=defs[key];
 if(type==="select")return `<div class="field"><label for="${id}">${label}<span class="required"> *</span></label><select id="${id}" class="control" required><option value="">Select...</option>${options.map(x=>`<option${x===value?" selected":""}>${x}</option>`).join("")}</select><div class="help">Same label and HTML ID on every workflow page</div></div>`;
 return `<div class="field"><label for="${id}">${label}<span class="required"> *</span></label><input id="${id}" class="control" type="${type}" value="${esc(value)}" required><div class="help">Same label and HTML ID on every workflow page</div></div>`;
}
function localField(module,[key,label,type="text",fallback=""],value=""){const id=localId(module,key);return `<div class="field"><label for="${id}">${label}<span class="required"> *</span></label><input id="${id}" class="control" type="${type}" value="${esc(value||fallback)}" required></div>`}
function generated([key,label],value=""){const id=defs[key]?.[0]||`nv-workflow-${key.replace(/[A-Z]/g,c=>`-${c.toLowerCase()}`)}`;return `<div class="field"><label for="${id}">${label}</label><input id="${id}" class="control generated-control" value="${esc(value)}" readonly><div class="help">Generated from submitted business data</div></div>`}
function stepper(module,state){const names=["Vendor record","Onboarding","Procurement","RFP","Purchase order","Contract"];return `<ol class="workflow-stepper">${workflowModules.map((key,i)=>`<li class="${key===module?"current":state.completed.includes(key)?"complete":""}"><span>${state.completed.includes(key)?"✓":i+1}</span>${names[i]}</li>`).join("")}</ol>`}
export function workflowPanel(module){
 if(!workflowModules.includes(module))return"";const state=load(),config=configs[module],values=module==="vendors"?state.source:(state.steps[module]||{});
 return `<section class="card workflow-card"><div class="card-head"><div><h2 class="card-title">Guided automation demo</h2><p class="workflow-caption">Step ${workflowModules.indexOf(module)+1} of 6</p></div><button id="nv-workflow-reset" class="btn danger spacer" type="button">Reset demo workflow</button></div>${stepper(module,state)}<div class="card-body"><div class="workflow-note">${config.help}</div><form id="nv-workflow-form" novalidate><div class="form-grid">${config.fields.map(f=>sharedField(f,values[f[0]])).join("")}${config.local.map(f=>localField(module,f,values[f[0]])).join("")}</div><h3 class="workflow-section-title">Generated workflow data</h3><div class="form-grid generated-grid">${config.generated.map(f=>generated(f,values[f[0]])).join("")}</div><div id="nv-workflow-validation-message" class="workflow-validation" role="status"></div><div class="toolbar workflow-actions"><button id="nv-workflow-save-draft" class="btn" type="button">Save draft</button><button id="nv-workflow-submit" class="btn primary" type="submit">Generate data and submit</button></div></form></div></section>`;
}
const read=id=>document.getElementById(id)?.value.trim()||"";
function collect(module){const config=configs[module],step={};for(const [key] of config.fields)step[key]=read(defs[key][0]);for(const [key] of config.local)step[key]=read(localId(module,key));return step}
function mismatch(value,expected,label,errors){if(expected&&String(value)!==String(expected))errors.push(`${label} does not match the recorded value.`)}
function validate(module,step,state){const e=[],s=state.source;if(module==="onboarding"){mismatch(step.vendorName,s.vendorName,"Vendor name",e);mismatch(step.vendorId,s.vendorId,"Vendor ID",e);mismatch(step.taxId,s.taxId,"Tax identifier",e)}if(!["vendors","onboarding"].includes(module)){if("vendorName" in step)mismatch(step.vendorName,s.vendorName,"Vendor name",e);if("vendorId" in step)mismatch(step.vendorId,s.vendorId,"Vendor ID",e);if("expectedSpend" in step)mismatch(step.expectedSpend,s.expectedSpend,"Expected annual spend",e);if("onboardingCaseId" in step)mismatch(step.onboardingCaseId,s.onboardingCaseId,"Onboarding case ID",e)}if(["rfps","purchase-orders","contracts"].includes(module))mismatch(step.procurementRequestId,state.steps.procurement?.procurementRequestId,"Procurement request ID",e);if(module==="purchase-orders")mismatch(step.rfpId,state.steps.rfps?.rfpId,"RFP ID",e);if(module==="contracts")mismatch(step.purchaseOrderId,state.steps["purchase-orders"]?.purchaseOrderId,"Purchase order ID",e);return e}
function enrich(module,x,state){const source=state.source,date=today(),code=hash(`${x.vendorName}|${x.taxId||source.taxId}`);if(module==="vendors")Object.assign(x,{vendorId:`VEN-${code}`,normalizedName:x.vendorName.toUpperCase().replace(/[^A-Z0-9 ]/g,"").replace(/\s+/g," "),riskTier:Number(x.expectedSpend)>=1000000?"Tier 1 — Critical":Number(x.expectedSpend)>=250000?"Tier 2 — Significant":"Tier 3 — Standard",createdDate:date});if(module==="onboarding"){const score=Math.min(100,25+(x.dataClassification==="Restricted"?35:x.dataClassification==="Confidential"?20:5)+(Number(x.personalDataVolume)>100000?25:10)+(x.criticalService.toLowerCase()==="yes"?15:0));Object.assign(x,{onboardingCaseId:`ONB-${date.slice(0,4)}-${code}`,onboardingDueDate:plus(date,score>=70?15:30),riskScore:`${score}/100`,reviewRoute:score>=70?"Procurement → Risk → Compliance → Legal":"Procurement → Risk"});Object.assign(state.source,x)}if(module==="procurement")Object.assign(x,{procurementRequestId:`PR-${date.slice(0,4)}-${code}`,budgetClassification:Number(x.expectedSpend)>=1000000?"Capital committee review":"Operating expenditure",approvalRoute:Number(x.expectedSpend)>=500000?"Department → Finance → Executive":"Department → Finance",createdDate:date});if(module==="rfps")Object.assign(x,{rfpId:`RFP-${date.slice(0,4)}-${code}`,issueDate:date,responseDeadline:plus(date,x.responseDays),commercialWeight:`${100-Number(x.technicalWeight)}%`});if(module==="purchase-orders")Object.assign(x,{purchaseOrderId:`PO-45${code}`,purchaseOrderDate:date,purchaseOrderTotal:money(x.expectedSpend),purchaseOrderStatus:Number(x.expectedSpend)>=500000?"Pending executive release":"Released"});if(module==="contracts"){const end=new Date(`${date}T12:00:00`);end.setMonth(end.getMonth()+Number(x.termMonths));Object.assign(x,{contractId:`CTR-${date.slice(0,4)}-${code}`,startDate:date,endDate:end.toISOString().slice(0,10),reviewDate:plus(date,Math.max(30,Number(x.termMonths)*30-90))})}}
export function bindWorkflow(module,refresh){if(!workflowModules.includes(module))return;const form=document.getElementById("nv-workflow-form"),message=document.getElementById("nv-workflow-validation-message");document.getElementById("nv-workflow-reset").onclick=()=>{localStorage.removeItem(KEY);refresh("Demo workflow reset.")};document.getElementById("nv-workflow-save-draft").onclick=()=>{const state=load();state.steps[module]={...(state.steps[module]||{}),...collect(module)};save(state);message.className="workflow-validation success";message.textContent="Draft saved. Generated values are created on submission."};form.onsubmit=event=>{event.preventDefault();if(!form.checkValidity()){form.reportValidity();return}const state=load(),step=collect(module),errors=validate(module,step,state);if(errors.length){message.className="workflow-validation error";message.innerHTML=errors.map(x=>`<div>${esc(x)}</div>`).join("");return}enrich(module,step,state);state.steps[module]=step;if(module==="vendors")state.source={...step};if(!state.completed.includes(module))state.completed.push(module);save(state);refresh(`Step ${workflowModules.indexOf(module)+1} completed. Generated data is ready to record and reuse.`)}}
